sudo: enabled
dist: trusty

language: python
python:
  - "3.6"

install:
  - pip install regex lxml requests textile cssselect jinja2

cache:
  yarn: true
  pip: true
  custom_install: true
  directories:
    - node_modules

# before_install:
#   - sudo add-apt-repository ppa:bauruine/sshpass -y
#   - sudo apt-get update -q

# addons:
#   apt:
#     packages:
#       - "sshpass"

before_script:
  - (cd ast && yarn)
  - (cd telegram && yarn)
  - sudo chmod +x ./script/build.sh

script: python3 ./script/build.py
